name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: installing wxgtk
      run: sudo apt search libwxgtk3.0-gtk3-dev
    - name: compailing
      run: g++ *.cpp `wx-config --cxxflags --libs`
