name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: libgtk-3-dev installing     
#      run: sudo apt install build-essential
#          |sudo apt install libgtk-3-dev 
    - name: configure
      run: sudo apt install libwxgtk3.0-gtk3-dev 
          | echo wxWidgets installed
    - name: building app
      run: g++ *.cpp `wx-config --cxxflags --libs`
          | echo app builded
    - name: running app
      run: echo ci executed successfully 
#      run: ./a.out 
